### ISSUE TITLE
Cannot resolve 'file' or 'directory' ../../../__sample.json 

### ISSUE THREAD

**Issue by chchiou** [vbarbarosh/app_google_drive_explorer#1]
Hi vbarbarosh,

While typing the command gulp, an error message appears as follows

'ERROR in ./src/static/js/app.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../__sample.json in /Documents/app_google_drive_explorer/src/static/js
 @ ./src/static/js/app.jsx 105:18-51'

It seems __sample.json is missing. How could I solve the problem?
Thank you.

**Comment by vbarbarosh** [comment]
Hi chchiou,

I'm still working on it. For now just replace ``require('../../../__sample.json')`` with ``[]``. ``__sample.json`` represents a list of flies fetched form Google Drive. I've saved it to a file just to not fetch it again and again after each recompilation.

**Comment by chchiou** [comment]
Thank you, the building problem is solved.
